### PR TITLE
US-0000011: Demo: Build the Business a Great New Feature

### PR DESCRIPTION
**Pull request by swongcopado**
BlingBling new feature added. Please review the controller code here.

### CODE REVIEW

**Review by andy-stevenckwong — COMMENTED** [review]
Code logic is fine but took me a while to review it. 
Please add some more documentation.

**Comment by swongcopado** [comment]
This code is hard to read. Please add some documentation to facilitate review

**Comment by andy-stevenckwong** [comment]
I agree. This needs to be better documented. Please do that and resubmit for review.

**Comment by swongcopado** [comment]
Alright. Code has been better documented now.

**Comment by andy-stevenckwong** [comment]
OK, this is way much better. Will approve.

**Review by andy-stevenckwong — APPROVED** [review]
Approved

**Pull request closed without merging**
