### PR TITLE
US-0000013: Build the Business something Great!

### PR DESCRIPTION
**Pull request by swongcopado**
Please review the code

### CODE REVIEW

**Comment by andy-stevenckwong** [comment]
Jermaine is working on the same code. Please collaborate with him on this.

**Comment by swongcopado** [comment]
Checked with him. He says to continue working on my thread and we will merge the conflict later.
Please review that my code is ready to go.

**Review by andy-stevenckwong — COMMENTED** [review]
OK, reviewing now.

**Comment by andy-stevenckwong** [comment]
Code looks ready to go. Approved

**Review by andy-stevenckwong — APPROVED** [review]
This is approved

**Pull request closed without merging**
